apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-main-config
data:
  httpd.conf: |
    ServerRoot "/usr/local/apache2"
    Listen 80
    ServerName localhost

    # Load required modules
    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule dir_module modules/mod_dir.so
    LoadModule rewrite_module modules/mod_rewrite.so
    LoadModule alias_module modules/mod_alias.so
    LoadModule log_config_module modules/mod_log_config.so
    LoadModule unixd_module modules/mod_unixd.so

    # Basic configuration
    User daemon
    Group daemon

    <Directory />
        AllowOverride none
        Require all denied
    </Directory>

    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # Logging configuration
    ErrorLog /proc/self/fd/2
    LogLevel warn
    CustomLog /proc/self/fd/1 combined

    # Include our custom redirects configuration
    Include conf/redirects.conf 